django_sharing_local/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("main_module.urls")),
    path('accounts/', include("account_module.urls")),
    path('contact/', include("contact_module.urls")),
    path('polls/', include("poll_module.urls")),
    path('news/', include("news_module.urls")),
    path('gallery/', include("gallery_module.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.GalleryCategoryListView.as_view(), name='gallery_category_list_view'),
    path("add/", views.GalleryAddView.as_view(), name='gallery_category_add'),
    path("<int:category_id>/", views.GalleryListView.as_view(), name='gallery_list_view'),
    path("<int:category_id>/add-image/", views.GalleryAddImageView.as_view(), name='gallery_add_image'),
    path("<int:category_id>/add-video/", views.GalleryAddVideoView.as_view(), name='gallery_add_video'),

]

main_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_view"),
    path("test/", views.TestView.as_view(), name="test_view"),
    path("events/", views.EventListView.as_view(), name="event_list_view"),
    path("events/<int:pk>/", views.EventDetailView.as_view(), name="event_detail_view"),
    path('events/delete/<int:pk>/', views.EventDeleteView.as_view(), name='event_delete_view'),
    path("events/add/", views.EventAddView.as_view(), name="event_add_view"),
    path("birthdays/", views.BirthdayListView.as_view(), name="birthday_list_view"),
    path("birthdays/add/", views.BirthdayAddView.as_view(), name="birthday_add_view"),
    path("birthdays/<int:pk>/", views.BirthdayDetailView.as_view(), name="birthday_detail_view"),
    path("files/", views.FileListView.as_view(), name="file_list_view"),
    path("files/add/", views.FileAddView.as_view(), name="file_add_view"),
    path('files/delete/<int:pk>/', views.FileDeleteView.as_view(), name='file_delete_view'),
    path("login-report", views.LoginReportView.as_view(), name="login_report_view"),
    path("logout-report", views.LogoutReportView.as_view(), name="logout_report_view"),
]

gallery_module/models.py
from django.db import models


# Create your models here.

class GalleryCategory(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان دسته بندی')
    description = models.TextField(verbose_name='توضبحات')
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی گالری'
        verbose_name_plural = 'دسته بندی های گالری'


class GalleryImage(models.Model):
    category = models.ForeignKey("GalleryCategory", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/gallery")
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'تصویر گالری'
        verbose_name_plural = 'تصاویر گالری'


class GalleryVideo(models.Model):
    category = models.ForeignKey("GalleryCategory", on_delete=models.CASCADE)
    video = models.FileField(upload_to="video/gallery")
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'ویدیو گالری'
        verbose_name_plural = 'ویدیو های گالری'

gallery_module/forms.py
from django import forms

from gallery_module.models import GalleryCategory, GalleryImage, GalleryVideo


class GalleryCategoryForm(forms.ModelForm):
    class Meta:
        model = GalleryCategory
        fields = ['title', 'description']


class GalleryAddImageForm(forms.ModelForm):
    class Meta:
        model = GalleryImage
        fields = ['title', 'image']
        # widgets = {
        #     'category': forms.Select(attrs={"class": "form-data"})
        # }


class GalleryAddVideoForm(forms.ModelForm):
    class Meta:
        model = GalleryVideo
        fields = ['title', 'video']

gallery_module/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView

from account_module.mixins import JustSuperUser
from gallery_module.forms import GalleryCategoryForm, GalleryAddImageForm, GalleryAddVideoForm
from gallery_module.models import GalleryCategory


# Create your views here.
class GalleryCategoryListView(LoginRequiredMixin, ListView):
    model = GalleryCategory
    template_name = 'gallery_module/gallery_category_list.html'
    context_object_name = 'gallerycategories'
    ordering = ["-created_at"]


class GalleryListView(LoginRequiredMixin, View):
    def get(self, request, category_id):
        gallery_category = get_object_or_404(GalleryCategory, pk=category_id)
        context = {
            'gallery_category': gallery_category
        }
        return render(request, 'gallery_module/gallery_list.html', context)


class GalleryAddView(JustSuperUser, View):
    def get(self, request):
        form = GalleryCategoryForm()
        context = {
            "form": form
        }
        return render(request, 'gallery_module/gallery_category_add.html', context)

    def post(self, request):
        form = GalleryCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("gallery_category_list_view"))
        context = {
            "form": form
        }
        return render(request, 'gallery_module/gallery_category_add.html', context)


class GalleryAddImageView(JustSuperUser, View):
    def get(self, request, category_id):
        form = GalleryAddImageForm()
        gallery_category = get_object_or_404(GalleryCategory, pk=category_id)
        context = {
            "form": form,
            'gallery_category': gallery_category
        }
        return render(request, 'gallery_module/gallery_add_image.html', context)

    def post(self, request, category_id):
        form = GalleryAddImageForm(request.POST, request.FILES)
        gallery_category = get_object_or_404(GalleryCategory, pk=category_id)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.category = gallery_category
            new_image.save()
            return redirect(reverse("gallery_list_view", kwargs={"category_id": category_id}))
        context = {
            "form": form,
            'gallery_category': gallery_category
        }
        return render(request, 'gallery_module/gallery_add_image.html', context)


class GalleryAddVideoView(JustSuperUser, View):
    def get(self, request, category_id):
        form = GalleryAddVideoForm()
        gallery_category = get_object_or_404(GalleryCategory, pk=category_id)
        context = {
            "form": form,
            'gallery_category': gallery_category
        }
        return render(request, 'gallery_module/gallery_add_video.html', context)

    def post(self, request, category_id):
        form = GalleryAddVideoForm(request.POST, request.FILES)
        gallery_category = get_object_or_404(GalleryCategory, pk=category_id)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.category = gallery_category
            new_image.save()
            return redirect(reverse("gallery_list_view", kwargs={"category_id": category_id}))
        context = {
            "form": form,
            'gallery_category': gallery_category
        }
        return render(request, 'gallery_module/gallery_add_video.html', context)

gallery_module/templates/gallery_module/gallery_add_image.html
{% extends 'shared/admin_layout.html' %}
{% load static %}
{% block content %}
    <div class="">
        <div class="clearfix"></div>
        <div class="main-row-container row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_content">
                    <br/>
                    <div class="article-container">
                        <div class="article-title">
                            {% if request.user.is_superuser %}
                                <a href="{% url 'gallery_add_image' category_id=gallery_category.id %}" class="add-newfile-btn">افزودن تصویر جدید</a>
                            {% endif %}
                            <h1>اضافه دسته بندی گالری</h1>
                            {% if request.user.is_superuser %}
                                <a href="{% url 'home_view' %}" class="go-to-home-page-btn">رفتن به صفحه اصلی</a>
                            {% endif %}
                        </div>
                        <div class="events-container">
                            <form style="width: 80%;margin: 0 auto" class="file-add-form" method="post"
                                  action="{% url 'gallery_add_image' category_id=gallery_category.id %}" enctype="multipart/form-data">
                                {% csrf_token %}
{#                                <div class="file-add-input-group">#}
{#                                    <label for=""> توضیحات دسته بندی : </label>#}
{#                                    {{ form.category }}#}
{#                                </div>#}
                                <div class="file-add-input-group">
                                    <label for="">عنوان تصویر :</label>
                                    {{ form.title }}
                                </div>
                                <div class="file-add-input-group">
                                    <label for=""> تصویر : </label>
                                    {{ form.image }}
                                </div>

                                <button type="submit">تایید</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

gallery_module/templates/gallery_module/gallery_add_video.html
{% extends 'shared/admin_layout.html' %}
{% load static %}
{% block content %}
    <div class="">
        <div class="clearfix"></div>
        <div class="main-row-container row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_content">
                    <br/>
                    <div class="article-container">
                        <div class="article-title">
                            {% if request.user.is_superuser %}
                                <a href="{% url 'gallery_add_image' category_id=gallery_category.id %}"
                                   class="add-newfile-btn">افزودن تصویر جدید</a>
                            {% endif %}
                            <h1>اضافه دسته بندی گالری</h1>
                            {% if request.user.is_superuser %}
                                <a href="{% url 'gallery_add_video' category_id=gallery_category.id %}" class="go-to-home-page-btn">رفتن به صفحه اصلی</a>
                            {% endif %}
                        </div>
                        <div class="events-container">
                            <form style="width: 80%;margin: 0 auto" class="file-add-form" method="post"
                                  action="{% url 'gallery_add_video' category_id=gallery_category.id %}"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                {#                                <div class="file-add-input-group">#}
                                {#                                    <label for=""> توضیحات دسته بندی : </label>#}
                                {#                                    {{ form.category }}#}
                                {#                                </div>#}
                                <div class="file-add-input-group">
                                    <label for="">عنوان ویدیو :</label>
                                    {{ form.title }}
                                </div>
                                <div class="file-add-input-group">
                                    <label for=""> ویدیو : </label>
                                    {{ form.video }}
                                </div>

                                <button type="submit">تایید</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

gallery_module/templates/gallery_module/gallery_category_add.html
{% extends 'shared/admin_layout.html' %}
{% load static %}
{% block content %}
    <div class="">
        <div class="clearfix"></div>
        <div class="main-row-container row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_content">
                    <br/>
                    <div class="article-container">
                        <div class="article-title">
                            {% if request.user.is_superuser %}
                                <a href="{% url 'event_add_view' %}" class="add-newfile-btn">افزودن دسته بندی جدید</a>
                            {% endif %}
                            <h1>اضافه دسته بندی گالری</h1>
                            {% if request.user.is_superuser %}
                                <a href="{% url 'home_view' %}" class="go-to-home-page-btn">رفتن به صفحه اصلی</a>
                            {% endif %}
                        </div>
                        <div class="events-container">
                            <form style="width: 80%;margin: 0 auto" class="file-add-form" method="post" action="{% url 'gallery_category_add' %}">
                                {% csrf_token %}
                                <div class="file-add-input-group">
                                    <label for="">عنوان دسته بندی :</label>
                                    {{ form.title }}
                                </div>
                                <div class="file-add-input-group">
                                    <label for=""> توضیحات دسته بندی : </label>
                                    {{ form.description }}
                                </div>

                                <button type="submit">تایید</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

gallery_module/templates/gallery_module/gallery_category_list.html
{% extends 'shared/admin_layout.html' %}
{% load static %}
{% block content %}
    <div class="">
        <div class="clearfix"></div>
        <div class="main-row-container row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_content">
                    <br/>
                    <div class="article-container">
                        <div class="article-title">
                            {% if request.user.is_superuser %}
                                <a href="{% url 'event_add_view' %}" class="add-newfile-btn">افزودن دسته بندی جدید</a>
                            {% endif %}
                            <h1>دسته بندی گالری رسانه ها</h1>
                            {% if request.user.is_superuser %}
                                <a href="{% url 'home_view' %}" class="go-to-home-page-btn">رفتن به صفحه اصلی</a>
                            {% endif %}
                        </div>
                        <div class="events-container">
                            {% for gallerycategory in gallerycategories %}
                                <a href="{% url 'gallery_list_view' category_id=gallerycategory.id %}" class="box-shadow-3d gallery-category-item">
                                    {% if gallerycategory.galleryimage_set.first.image %}
                                        <img src="{{ gallerycategory.galleryimage_set.first.image.url }}" alt="">
                                    {% else %}
                                        <img src="{% static 'images/empty.jpg' %}" alt="">
                                    {% endif %}
                                    <p class="gallery-category-title">
                                        {{ gallerycategory.title }}
                                    </p>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

gallery_module/templates/gallery_module/gallery_list.html
{% extends 'shared/admin_layout.html' %}
{% load static %}
{% block content %}
    <div class="">
        <div class="clearfix"></div>
        <div class="main-row-container row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_content">
                    <br/>
                    <div class="article-container">
                        <div class="article-title">
                            {% if request.user.is_superuser %}
                                <a href="{% url 'gallery_add_image' category_id=gallery_category.id %}" class="add-newfile-btn">افزودن تصویر جدید</a>
                            {% endif %}
                            <h1>عکس ها و ویدیو های {{ gallery_category.title }}</h1>
                            {% if request.user.is_superuser %}
                                <a href="{% url 'gallery_add_video' category_id=gallery_category.id %}" class="go-to-home-page-btn">افزودن ویدیو جدید</a>
                            {% endif %}
                        </div>
                        <div class="gallery_category_description">
                            {{ gallery_category.description }}
                        </div>
                        <div class="events-container">
                            {% for gallery_image in gallery_category.galleryimage_set.all %}
                                <a href="{{ gallery_image.image.url }}"
                                   class="gallery-category-item">
                                    {% if gallery_image.image %}
                                        <img src="{{ gallery_image.image.url }}" alt="">
                                    {% else %}
                                        <img src="{% static 'images/empty.jpg' %}" alt="">
                                    {% endif %}
                                    <p class="gallery-category-title">
                                        {{ gallery_image.title }}
                                    </p>
                                </a>
                            {% endfor %}
                            {% for gallery_video in gallery_category.galleryvideo_set.all %}
                                <div href="{{ gallery_video.video.url }}"
                                   class="gallery-category-item">
                                    {% if gallery_video.video %}
                                        <video src="{{ gallery_video.video.url }}" controls>
                                            <source
                                                    src="{{ gallery_video.video.url }}"
                                                    type="video/mp4"/>
                                        </video>
                                    {% else %}
                                        <img src="{% static 'images/empty.jpg' %}" alt="">
                                    {% endif %}
                                    <p class="gallery-category-title">
                                        {{ gallery_video.title }}
                                    </p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}